# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: 自动构建并发布包到 npm

on:
  push:
    branches:
      - master

# 权限配置
permissions:
  id-token: write # Required for OIDC
  contents: write # 允许仓库内容修改，用于创建 标签和版本

jobs:
  build-and-publish-npm:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4

      - name: 安装 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: 使用 Node.js ${{ matrix.node-version }} 版本
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Update npm
        run: npm install -g npm@latest

      - name: 安装依赖
        run: pnpm install

      - name: 构建
        run: pnpm run build

      - name: 迭代版本号
        run: node ./dist_node/iteration-version.js -m ${{vars.MAJOR_VN}} -n ${{vars.MINOR_VN}}

      - name: 发布包到 npm
        run: pnpm publish -r --access public --no-git-checks

      - name: Read version from package.json
        id: read_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.read_version.outputs.VERSION  }}
          release_name: Release v${{ steps.read_version.outputs.VERSION }}
          draft: false
          prerelease: false
